<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pratik" name="Default test" tests="5" failures="1" timestamp="2 Aug 2016 08:23:10 GMT" time="5.895" errors="0">
  <testcase name="login" time="3.89" classname="CallReport.SaveCallReport"/>
  <testcase name="homePage" time="0.03" classname="CallReport.SaveCallReport">
    <failure type="java.lang.AssertionError" message="Possible defect - Home page title mismatch. expected [Salesforce - Enterprise Edition] but found []">
      <![CDATA[java.lang.AssertionError: Possible defect - Home page title mismatch. expected [Salesforce - Enterprise Edition] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at CallReport.SaveCallReport.homePage(SaveCallReport.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- homePage -->
  <testcase name="accountHolder" time="0.001" classname="CallReport.SaveCallReport">
    <skipped/>
  </testcase> <!-- accountHolder -->
  <testcase name="saveCallRreport" time="0.001" classname="CallReport.SaveCallReport">
    <skipped/>
  </testcase> <!-- saveCallRreport -->
  <testcase name="logout" time="0.001" classname="CallReport.SaveCallReport">
    <skipped/>
  </testcase> <!-- logout -->
</testsuite> <!-- Default test -->
